name: Master Workflow

on:
  workflow_dispatch:

# on: [push]

jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow_dispatch
        # env:
        #   GH_TOKEN: JsTJlhM12TtkIMQLSoZaKUXhc2n5k43zGaX7
        #   TARGET_OWNER: Fesfouss
        #   TARGET_REPO: awesome
        #   TARGET_WORKFLOW: main.yml
        #   TARGET_REF: main
        run: |
          # sudo iptables -L -n -v
          cat /proc/sys/net/ipv4/conf/all/rp_filter
          sudo sysctl -w net.ipv4.conf.all.rp_filter=0
          sudo sysctl -w net.ipv4.conf.default.rp_filter=0
          sudo sysctl -w net.ipv4.conf.eth0.rp_filter=0
          cat /proc/sys/net/ipv4/conf/all/rp_filter
          curl ipinfo.io
