name: Master Workflow

on:
  workflow_dispatch:

# on: [push]

jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow_dispatch
        # env:
        #   GH_TOKEN: JsTJlhM12TtkIMQLSoZaKUXhc2n5k43zGaX7
        #   TARGET_OWNER: Fesfouss
        #   TARGET_REPO: awesome
        #   TARGET_WORKFLOW: main.yml
        #   TARGET_REF: main
        run: |

          curl ipinfo.io
