on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  call-matrix-workflow:
    uses: Buc014960kPearson/Buc014960kPearson/.github/workflows/dynamic-matrix-runner.yml@main
    with:
      start_index: 1
      total_jobs: 80

  xx:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger B workflow_dispatch
        env:
          GH_TOKEN: EU2ilMizH3lwRM5iFOmVoYZ4C24BZd1hEXAG
          TARGET_OWNER: benasff
          TARGET_REPO: benasff
          TARGET_WORKFLOW: test.yml
          TARGET_REF: main
        run: |
          WORKFLOW_INPUTS="{\"start_index\":\"41\",\"total_jobs\":\"80\",\"run_id\":${{ github.run_id }}}"
          echo $WORKFLOW_INPUTS

          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ghp_$GH_TOKEN" \
            https://api.github.com/repos/$TARGET_OWNER/$TARGET_REPO/actions/workflows/$TARGET_WORKFLOW/dispatches \
            -d "{\"ref\":\"$TARGET_REF\",\"inputs\":$WORKFLOW_INPUTS}"