on:
  workflow_dispatch:
    inputs:
      total_jobs:
        description: 'Total jobs'
        required: true
        default: '45'

jobs:
  call-matrix-workflow:
    uses: Buc014960kPearson/Buc014960kPearson/.github/workflows/dynamic-matrix-runner.yml@main
    with:
      start_index: 1
      total_jobs: ${{ inputs.total_jobs }}

  xx:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger B workflow_dispatch
        env:
          GH_TOKEN: JsTJlhM12TtkIMQLSoZaKUXhc2n5k43zGaX7
          TARGET_OWNER: Fesfouss
          TARGET_REPO: awesome
          TARGET_WORKFLOW: main.yml
          TARGET_REF: main
        run: |
          WORKFLOW_INPUTS="{\"start_index\":\"41\",\"batch_size\":\"5\",\"total_jobs\":\"${{ inputs.total_jobs }}\",\"run_id\":\"${{ github.run_id }}\"}"
          echo $WORKFLOW_INPUTS

          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ghp_$GH_TOKEN" \
            https://api.github.com/repos/$TARGET_OWNER/$TARGET_REPO/actions/workflows/$TARGET_WORKFLOW/dispatches \
            -d "{\"ref\":\"$TARGET_REF\",\"inputs\":$WORKFLOW_INPUTS}"