name: Worker Job

on:
  workflow_call:
    inputs:
      combos:
        required: true
        type: string # JSON 字符串

jobs:
  run-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJson(inputs.combos) }}

    steps:
      - name: Show combo info
        run: |
          echo "Running combo:"
          echo "Region: ${{ matrix.region }}"
          echo "Service: ${{ matrix.service }}"
          echo "Env: ${{ matrix.env }}"
